### ISSUE TITLE
Last item cannot be removed for self-relationship

### ISSUE THREAD

**Issue by AArmin** [armincms/many-to-many#1]
I have a self relationship, product to product, and I get the display of products, I'm able to search, add, remove, add pivot fields, however - the last item cannot be removed from the list.

**Comment by zareismail** [comment]
Hi. thanks for reporting
Will be resolved soon

**Comment by zareismail** [comment]
Resolved in release [0.2.1](https://github.com/armincms/many-to-many/releases/tag/0.2.1)
