### ISSUE TITLE
Code isn't working when routes are cached

### ISSUE THREAD

**Issue by glamorous** [armincms/many-to-many#14]
Reason is that you use the same pattern for routes that is already provided by Nova by default.

The route "nova-api/armincms/{resource}/attachable/{field}" is never reached because of the default route of Laravel Nova: "nova-api/{resource}/{resourceId}/attachable/{field}" that matches the same "rules" but "armincms" is the "resource" and so Nova aborts the request because the resource wasn't found.

A "quick" fix would be to rename your route so "attachable" isn't being used.

**Comment by SadeghPM** [comment]
Hi @zareismail 
This is serious problem that cause package don't work at all.
