### ISSUE TITLE
Why Do we need an id field on the pivot table?

### ISSUE THREAD

**Issue by roarkmccolgan** [armincms/many-to-many#2]
Hi Guys!

Great package, thanks very much for the awesome work.
Just wondering why you would need an id field on the pivot table?

Reason I ask is my table setup looks like so:
```php
Schema::create('product_property', function (Blueprint $table) {
    $table->foreignId('product_id');
    $table->foreignId('property_id');
    $table->integer('price');
    $table->primary(['product_id', 'property_id']);
});
```
Using composite primary keys

Thanks!

**Comment by zareismail** [comment]
Hi. thanks for the report. 
The pivot id uses to detect which pivot is updating.
