### ISSUE TITLE
Searchable Relation

### ISSUE THREAD

**Issue by SadeghPM** [armincms/many-to-many#5]
Hi @zareismail 
First tanks for this greate tool.
Could you make it searchable like nova [Searchable Relation](https://nova.laravel.com/docs/3.0/resources/relationships.html#searchable-relations)?
Thanks

**Comment by bernhardh** [comment]
That would be great!

**Comment by zareismail** [comment]
Hi. Thanks for the reporting. 
It's a good idea, but I don't have enough time to implement it. maybe at next release I will work on it

**Comment by zareismail** [comment]
Hey. searchable is [here (version 0.3.0) ](https://github.com/armincms/many-to-many/releases/tag/0.3.0)
@bernhardh @SadeghPM

**Comment by SadeghPM** [comment]
Thank you @zareismail. Now we could use it on big collection 💥

**Comment by bernhardh** [comment]
Thank you very much!
